new_list = [1, 5 ,3]
print(new_list[1:])
new_list.append(6)
print(new_list)
new_list.append(2)
new_list.append(3)
new_list.pop()
print(new_list)
new_list.pop(1)
print(new_list)
new_list.sort()
print(new_list)
another_list = ['a', 'z', 'd', 'u', 'j', 'c']
another_list.sort()
print(another_list)
another_list.reverse()
print(another_list)